import re
from nltk.corpus import stopwords


# Grad all general stop words
STOPWORDS = set(stopwords.words('english'))

#specifiaction
BRANCH=[
    'CHEMICAL','MINING','AERONAUTICAL','TEXTILE','MECHATRONICS','CIVIL',
    'ELECTRONICS','COMMUNICATION','ROBOTICS','POWER','AEROSPACE','MECHANICAL',
    'STRUCTURAL','INDUSTRIAL','MARINE','PETROLEUM','AUTOMOBILE','PRODUCTION',
    'METALLURGICAL','CERAMIC','BIOMEDICAL','CONSTRUCTION','ELECTRONICS','TOOL'
    ,'TELECOMMUNICATION','ENVIRONMENTAL','TRANSPORTATION','ELECTRONICS AND COMMUNICATION'
    ,'BIOTECHNOLOGY','ELECTRICAL','COMPUTER','COMPUTER SCIENCE','CSE','ECE','EEE','ARC']

